name: sound_of_meme
description: "An assignment for Sound Of Meme demonstrating Clean Architecture with Bloc"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  lottie: ^1.4.3

  firebase_core: ^3.1.1
  firebase_remote_config: ^5.0.2
  equatable: ^2.0.5
  get_it: ^7.7.0
  device_info_plus: ^10.1.0
  platform: ^3.1.5
  internet_connection_checker: ^1.0.0+1
  dio: ^5.5.0+1
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  audio_session: ^0.1.21
  adaptive_theme: ^3.6.0
  fade_shimmer: ^2.2.0
  preload_page_view: ^0.2.0
  file_picker: ^8.0.6
  cached_network_image: ^3.4.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  http_parser: ^4.0.2
  flutter_native_splash: ^2.4.1
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/open_sans/
    - assets/locales/i18n/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pepe_logo.png
  color_dark: "#0F172A"
  image_dark: assets/images/pepe_logo.png

  android_12:
    image: assets/images/pepe_logo_24.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/pepe_logo_24.png
    icon_background_color_dark: "#0F172A"

  web: false

icons_launcher:
  image_path: "assets/images/pepe_logo_12.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


